Blog\UserBundle\Entity\User:
    type:  entity
    table: w_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        token:
            type: string
            length: 255
        photo:
            type: string
            length: 255
            nullable: true
        weibo_id:
            type: string
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setTokenValue ]