<?php

namespace Blog\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Blog\NewsBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getYesterdayNews()
    {
        $qb = $this->createQueryBuilder('n')->where('n.created_at > :date')
        			->setParameter('date', date('Y-m-d', time()));

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function getNews($date)
    {
        $qb = $this->createQueryBuilder('n')->where(' :after > n.created_at and n.created_at > :today')
        			->setParameter('after', date('Y-m-d', strtotime($date) + 3600*24))
        			->setParameter('today', date('Y-m-d', strtotime($date)));

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function getFourNews($offset)
    {
        $qb = $this->createQueryBuilder('n')->where('n.created_at > :date')
                           ->setParameter('date', date('Y-m-d', time()))
                           ->setMaxResults(4)
                           ->setFirstResult($offset*4);

        $query = $qb->getQuery();

        return $query->getResult();
    }

}
